; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.1
  	framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.1/esp32-arduino-libs-3.0.1.zip
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 9600
lib_deps = 
	lewapek/Nova Fitness Sds dust sensors library@^1.5.1
	adafruit/Adafruit BusIO@^1.16.2
	adafruit/RTClib@^2.1.4
	adafruit/Adafruit BME680 Library@^2.0.5
